### ISSUE TITLE
Users are getting disconnected when api is down

### ISSUE THREAD

**Issue by recon88** [pdaian/MCBouncer#15]
How can I avoid this?

```
2013-03-20 15:06:19 [SEVERE] java.net.UnknownHostException: www.mcbouncer.com: Name or service not known
2013-03-20 15:06:19 [SEVERE]    at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
2013-03-20 15:06:19 [SEVERE]    at java.net.InetAddress$1.lookupAllHostAddr(Unknown Source)
2013-03-20 15:06:19 [SEVERE]    at java.net.InetAddress.getAddressesFromNameService(Unknown Source)
2013-03-20 15:06:19 [SEVERE]    at java.net.InetAddress.getAllByName0(Unknown Source)
2013-03-20 15:06:19 [SEVERE]    at java.net.InetAddress.getAllByName(Unknown Source)
2013-03-20 15:06:19 [SEVERE]    at java.net.InetAddress.getAllByName(Unknown Source)
2013-03-20 15:06:19 [SEVERE]    at org.apache.http.impl.conn.DefaultClientConnectionOperator.resolveHostname(Unknown Source)
2013-03-20 15:06:19 [SEVERE]    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(Unknown Source)
2013-03-20 15:06:19 [SEVERE]    at org.apache.http.impl.conn.AbstractPoolEntry.open(Unknown Source)
2013-03-20 15:06:19 [SEVERE]    at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(Unknown Source)
2013-03-20 15:06:19 [SEVERE]    at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(Unknown Source)
2013-03-20 15:06:19 [SEVERE]    at org.apache.http.impl.client.DefaultRequestDirector.execute(Unknown Source)
2013-03-20 15:06:19 [SEVERE]    at org.apache.http.impl.client.AbstractHttpClient.execute(Unknown Source)
2013-03-20 15:06:19 [SEVERE]    at org.apache.http.impl.client.AbstractHttpClient.execute(Unknown Source)
2013-03-20 15:06:19 [SEVERE]    at org.apache.http.impl.client.AbstractHttpClient.execute(Unknown Source)
2013-03-20 15:06:19 [SEVERE]    at com.mcbouncer.http.Transport.sendURL(Unknown Source)
2013-03-20 15:06:19 [SEVERE]    at com.mcbouncer.api.MCBouncerAPI.getAPIURL(Unknown Source)
2013-03-20 15:06:19 [SEVERE]    at com.mcbouncer.api.MCBouncerAPI.updateUser(Unknown Source)
2013-03-20 15:06:19 [SEVERE]    at com.mcbouncer.event.listener.JoinListener.onEvent(Unknown Source)
2013-03-20 15:06:19 [SEVERE]    at com.mcbouncer.event.listener.JoinListener.onEvent(Unknown Source)
2013-03-20 15:06:19 [SEVERE]    at net.lahwran.fevents.MCBEventHandler.callEvent(Unknown Source)
2013-03-20 15:06:19 [SEVERE]    at com.mcbouncer.bukkit.BukkitPlayerListener.onPlayerPreLoginAsync(Unknown Source)
2013-03-20 15:06:19 [SEVERE]    at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
2013-03-20 15:06:19 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-03-20 15:06:19 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2013-03-20 15:06:19 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:392)
2013-03-20 15:06:19 [SEVERE]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
2013-03-20 15:06:19 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
2013-03-20 15:06:19 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:459)
2013-03-20 15:06:19 [SEVERE]    at iu.run(ThreadLoginVerifier.java:96)
2013-03-20 15:06:19 [SEVERE] [MCBouncer] MCBouncer timed out while looking up: recon_
2013-03-20 15:06:19 [INFO] Disconnecting recon_ [/XX.XX.XX.XX:51915]: MCBouncer timeout.
2013-03-20 15:06:28 recon_ [/XX.XX.XX.XX:51915] lost connection
```

**Comment by Deaygo** [comment]
If you are running the latest version, in the "plugins/MCBouncer/config.yml" file, add in a allowedOnFail: true

This will allow even banned people to join, just so you are aware.

**Comment by recon88** [comment]
Alright I will try.
I'm OK with that since it is a whitelisted server.

Is that the newest version?

```
[MCBouncer] Loading MCBouncer v1.3.1beta
```

**Comment by recon88** [comment]
Nevermind. Compiled the 1.3.2beta.

Thanks for the quick answer!
